packages:
  - apps/*
catalog:
  "@aaroon/workbox-rspack-plugin": ^0.3.2
  "@biomejs/biome": ^1.9.4
  "@rsbuild/core": ^1.3.1
  "@rsdoctor/rspack-plugin": ^1.0.2
  "@tailwindcss/postcss": ^4.1.4
  "@tsconfig/node-lts": ^22.0.1
  "@tsconfig/node-ts": ^23.6.1
  "@types/node": ^22.15.2
  esbuild: ^0.25.3
  rsbuild-plugin-html-minifier-terser: ^1.1.1
  sst: ^3.13.19
  tailwindcss: ^4.1.4
  tsx: ^4.19.3
  typescript: ^5.8.2
  wrangler: ^4.13.2
