name: Deploy App Web

on:
  push:
    branches:
      - main

env:
  NODE_VERSION: 22
  PUBLIC_API_URL: ${{ vars.PUBLIC_API_URL }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy App Web
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: 10

      - name: Setup Node ${{ env.NODE_VERSION }} Environment
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install

      - name: Build
        run: pnpm --filter @workspace/web build

      - name: Deploy
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          workingDirectory: "apps/web"
          command: pages deploy
